Repository hmcts/pdm-interfaces, pull requests merged in 2024-07, with the labels that each got.

#101 removed final keyword
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/pdm/business/entities/xhbcourt/XhbCourtDao.java
  src/main/java/uk/gov/hmcts/pdm/business/entities/xhbcourtroom/XhbCourtRoomDao.java
  src/main/java/uk/gov/hmcts/pdm/business/entities/xhbdisplay/XhbDisplayDao.java
  src/main/java/uk/gov/hmcts/pdm/business/entities/xhbrotationsets/XhbRotationSetsDao.java
  src/main/java/uk/gov/hmcts/pdm/publicdisplay/manager/dto/DisplayDto.java
  src/main/java/uk/gov/hmcts/pdm/publicdisplay/manager/dto/DisplayLocationDto.java
  src/main/java/uk/gov/hmcts/pdm/publicdisplay/manager/dto/DisplayTypeDto.java
  src/main/java/uk/gov/hmcts/pdm/publicdisplay/manager/dto/DynamicDropdownList.java
  src/main/java/uk/gov/hmcts/pdm/publicdisplay/manager/dto/DynamicDropdownOption.java
Labels: ns:pdda, prd:pdda, rel:pdda-public-display-manager-pr-101

#108 Feature/pdda 384
  build.gradle
Labels: ns:pdda, prd:pdda, rel:pdda-public-display-manager-pr-108

#112 pdda-392 Revert the smoketest to point to the main page
  src/functionalTest/java/uk/gov/hmcts/controller/LogonControllerFunctionalTest.java
  src/smokeTest/java/uk/gov/hmcts/controller/LogonControllerSmokeTest.java
Labels: ns:pdda, prd:pdda, rel:pdda-public-display-manager-pr-112

#125 adding azure client-id
  src/main/resources/application.properties
Labels: ns:pdda, prd:pdda, rel:pdda-public-display-manager-pr-125
